definitions:
  model.RequestCreateComment:
    properties:
      commentMessage:
        type: string
      createDateAt:
        type: integer
      exhibitionId:
        type: string
      updateDateAt:
        type: integer
      user:
        $ref: '#/definitions/model.User'
    required:
    - commentMessage
    - exhibitionId
    type: object
  model.RequestUpdateComment:
    properties:
      commentMessage:
        type: string
      updateDateAt:
        type: integer
    required:
    - commentMessage
    type: object
  model.User:
    properties:
      firstname:
        type: string
      id:
        type: string
      lastname:
        type: string
      profile:
        type: string
    type: object
info:
  contact: {}
  description: Comment Service สำหรับขอจัดการเกี่ยวกับ Workshop Manager ทั้งการสร้าง
    แก้ไข ลบ Workshop Manager
  title: Comment Service API
  version: v0
paths:
  /api/comments:
    post:
      consumes:
      - application/json
      description: Create a new comment
      operationId: CreateComment
      parameters:
      - description: Comment data to create
        in: body
        name: requestExhibition
        required: true
        schema:
          $ref: '#/definitions/model.RequestCreateComment'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Create a new comment
      tags:
      - Comments
  /api/comments/{id}:
    delete:
      consumes:
      - application/json
      description: DeleteCommentByID
      operationId: DeleteCommentByID
      parameters:
      - description: Comment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: DeleteCommentByID
      tags:
      - Comments
    get:
      consumes:
      - application/json
      description: GetCommentByID
      operationId: GetCommentByID
      parameters:
      - description: Comment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: GetCommentByID
      tags:
      - Comments
    put:
      consumes:
      - application/json
      description: Update a new comment
      operationId: UpdateComment
      parameters:
      - description: comment ID
        in: path
        name: id
        required: true
        type: string
      - description: Comment data to update
        in: body
        name: requestUpdateExhibition
        required: true
        schema:
          $ref: '#/definitions/model.RequestUpdateComment'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Update a new comment
      tags:
      - Comments
  /api/comments/exhibitions/{id}:
    get:
      consumes:
      - application/json
      description: GetCommentsByExhibitionID
      operationId: GetCommentsByExhibitionID
      parameters:
      - description: Exhibition ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: GetCommentsByExhibitionID
      tags:
      - Comments
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
